### ISSUE TITLE
a stream using ns.first can get stuck

### ISSUE THREAD

**Issue by catdad** [stezu/node-stream#2]
https://github.com/stezu/node-stream/blob/master/lib/consumers/v1/first.js#L16-L18

It won't flow past the first read... I think.

**Comment by stezu** [comment]
The act of attaching an event handler switches it into flowing mode. See here: https://github.com/nodejs/node/blob/master/lib/_stream_readable.js#L689

`EventEmitter.once` basically calls `EventEmitter.on` but only calls the callback once (and removes the listener). See here: https://github.com/nodejs/node/blob/master/lib/events.js#L301

In the end, `ReadableStream.on` is called with a `'data'` event, which switches it into flowing mode. That event listener is removed which `ReadableStream` doesn't care about. Unless the stream was paused before being sent to `ns.first`, this will work correctly (unit tests confirm that behavior).

I'll keep this bug open so I remember to add tests for paused streams.

**Comment by stezu** [comment]
So, I've decided to drop this since the API is legacy and no longer documented.

The main reasons for that decision are:
* The v1 API does not handle backpressure, it attaches a "data" event handler which makes the sending stream a firehose.
* The only method that survived to v2 was the `wait` method because it's the only one that provides utility with a simple API.

In Node, if you wanted to read all items from a stream with no regard to backpressure, you write something like the following (which is what the v1 API does):
```javascript
streamyThing
  .on('error', function (err) {
    console.error('sad trombone', err);
  })
  .on('data', function (chunk) {
    res.write(chunk);
  })
  .on('end', function () {
    res.end();
  });
```

The only reason I could think of for doing something like this is if you were fitting streams into an application that does not really support them. With the v2 API, I shifted focus to deal with everything in streams and am adding functionality I think would be useful to achieve that goal.
