### ISSUE TITLE
implement #throttle

### ISSUE THREAD

**Issue by catdad** [stezu/node-stream#7]
Throttle items being written to the stream, emitting an array of all items read on the stream, at the defined interval.

```javascrpit
ns.throttle(interval)
```

**Comment by catdad** [comment]
I have a bunch of questions about what you prefer:

1. Lodash takes an interval and an optional options object that defined `leading` or `trailing`. How do you feel about including that? The implementation I have no assumes `leading`, but I could see having an option be useful.

1. The implementation we have assumes that if the data that is received is already an array, it should `concat` it along with the existing items. How okay are you with that? Should there be a `throttle` that just throttles mixed types, and a `throttleFlat` (or something like that) that flattens arrays? Is flattening arrays even useful? We never actually used that functionality... I just kind of did it for no reason.

1. I feel like we talked about this, but the interval should be "at least `n` milliseconds since the last write", possibly allowing more time in between actual writes, right? I keep rewriting the interval logic for this, and I don't really see any of the implementations having a conceivable benefit over the others.

**Comment by stezu** [comment]
1. I think I like the lodash option of a second options argument. I've definitely modeled a few methods against lodash already and I don't think there's any reason not to continue that trend.
2. I would prefer a dumb method that doesn't flatten arrays. We can flatten arrays with a different method if we so choose (I think we spoke about a `#spread` method that would handle this).
3. What are the possible options here? It seems like the most logical one is where we have a definition of "approximately `n` milliseconds since the last write if there's data". We obviously can't guarantee exact timing, but we also want to stipulate we're trying to write data when the caller wants it. I think that's the implementation you already have, but I'm not certain.

Also, I think we need to rename this method. Highland uses [batchWithTimeOrCount](http://highlandjs.org/#batchWithTimeOrCount). Bacon.js uses a whole bunch of different methods with a name containing buffer: [bufferWithTime](https://github.com/baconjs/bacon.js/blob/master/README.md#stream-bufferwithtime), [bufferWithCount](https://github.com/baconjs/bacon.js/blob/master/README.md#stream-bufferwithcount), [bufferWithTimeOrCount](https://github.com/baconjs/bacon.js/blob/master/README.md#stream-bufferwithtimeorcount), and [bufferingThrottle](https://github.com/baconjs/bacon.js/blob/master/README.md#observable-bufferingthrottle). RxJS uses most of the same methods as Bacon to achieve this effect that you're describing.

`#throttle` however does something totally different in those libraries: [RxJS](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/throttle.md), [Bacon](https://github.com/baconjs/bacon.js#observable-throttle), [Highland](http://highlandjs.org/#throttle).

**Comment by stezu** [comment]
Also, as an aside, the reactive libraries don't use `spread`. [Highland uses `flatten`](http://highlandjs.org/#flatten), [RxJS uses some strangeness](http://stackoverflow.com/a/37540941). I assume Bacon is similar to RxJS.

And I realize this is all somewhat conflicting information and I haven't really decided on an approach. This is basically a stream of consciousness and doesn't mean much. At this point, I'm really curious which direction you think we should go given the above information.

**Comment by catdad** [comment]
1. Cool. That's what I thought. Except, see #8 now, since that might change things.

1. Yeah, when I think about it more, I have no idea why I made it concat arrays in text-service... it doesn't even use it. Simple is better 👍.

1. I've actually lost track on this. The naive solution (I think this is what I have right now) is to set a timeout when we read some data for the requested time, and push the data to an array. If a timeout already exists, just push the data to the array. When the timeout executes, make sure to set it to `null` so a new timeout is created on the next read. This is more or less fine, except if your source stream is already throttled to the correct time. Then, we would put extra throttle on it, because in reality, it is executing at `n milliseconds since the last read`, rather than `n milliseconds between writes`. Instead, we could save the last write and then set timeouts based on `now + timeout - lastWrite` (or whatever the actual math is there). Of course, neither can actually be tested well enough, since timing tests always fail... so does anyone even care?

I kind of like `flatten`. Lodash goes a bit further (with array's only, obviously) and has a `flatten` which is one level, `flattenDeep` which recursively flattens all levels (which is the `flatten` version in Highland), and a `flattenDepth` where you can tell it how many levels to flatten. I can definitely see a need to only flatten a single level rather than all levels (e.g. `throttle` only creates one level of arrays, so you would just want to reverse one level in `flatten` so you don't break all the things). I forgot to create an issue for `flatten`/`spread`, so maybe this needs to move to a new issue there.

**Comment by catdad** [comment]
Okay, I need to read more carefully. I see what you mean about the name. Those `throttle` methods do not change the values in the stream, but only the time between writes. So really, what I have been talking about all along is what I mentioned in #8, except everything is a `batch({ time, count })` thing.

I might be weird, but I kind of don't like having different names with single properties in them. i.e.:

`batch({ count: 5 })` > `batchWithCount(5)`
`batch({ time: 30 })` > `batchWithTime(30)`
`batch({ count: 5, time: 30 })` > `batchWithTimeOrCount(5, 30)`

Is it just me, or do all those names seem silly?

**Comment by stezu** [comment]
I think `batch({ count: 5, time: 30 })` seems like the right approach. And to reverse the batching, I think a single level `flatten` also works. Meta streams or multi-level arrays can be safely ignored for now.

**Comment by stezu** [comment]
Closing this since #13, #8 is where the actual work is being done.
